---
version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: 'h3.settings.production'
    restart: always
    volumes:
      - static_volume:/code/h3/static
    depends_on:
      - database
  database:
    image: "mysql:5.7"
    restart: always
    environment:
      MYSQL_DATABASE: 'django'
      MYSQL_USER: 'django'
      MYSQL_PASSWORD: 'django'
      MYSQL_ROOT_PASSWORD: 'django'
    ports:
      - '3306:3306'
    volumes:
      - ./db-contents:/var/lib/mysql
  nginx:
    build:
      context: ./nginx
    restart: always
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
