# Generated by Django 2.2.7 on 2019-11-06 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='schedule',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Schedules'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(blank=True, to='classes.Students'),
        ),
    ]
