# Generated by Django 2.2.7 on 2019-11-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20191106_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='classes.Students'),
        ),
    ]
