# Generated by Django 2.2.7 on 2019-11-06 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20191106_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Schedules'),
        ),
    ]
