# Generated by Django 2.2.7 on 2019-11-06 23:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0004_auto_20191106_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
