# Generated by Django 2.2.7 on 2019-11-06 23:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_courses_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
