# Generated by Django 2.2.7 on 2019-11-06 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_courses_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='schedule',
        ),
        migrations.AddField(
            model_name='courses',
            name='datepattern',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Schedules',
        ),
    ]
